version: "3.8"

services:
  web:
    build: ./sbm_backend
    command: sh -c "uv run manage.py migrate && uv run gunicorn sbm_backend.wsgi:application -c gunicorn.conf.py"
    volumes:
      - ./sbm_backend:/usr/src/sbm_backend
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  db:
    image: postgres:15.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=sbmdb
    pull_policy: always

volumes:
  postgres_data:
