# Generated by Django 5.2.6 on 2025-09-09 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_cryptomarketdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CryptoMarketData',
        ),
    ]
